import type { Metadata } from 'next'
import { Suspense } from 'react'
import { Skeleton } from '@/components/ui/skeleton'
import { Toaster } from '@/components/ui/sonner'
import { ThemeProvider } from '@/components/theme-provider'
import { AuthProvider } from '@/components/auth-context'
import './globals.css'

export const metadata: Metadata = {
  title: 'Nexus',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className="scrollbar">
        <ThemeProvider attribute="class">
          <AuthProvider>
            <Suspense
              fallback={
                <Skeleton className="min-h-screen flex items-center justify-center" />
              }
            >
              {children}
            </Suspense>
            <Toaster />
          </AuthProvider>
        </ThemeProvider>
      </body>
    </html>
  )
}
